
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KC
 */
public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();    
    }
    DefaultTableModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_id = new javax.swing.JTextField();
        jTextField_totalprice = new javax.swing.JTextField();
        jTextField_change = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_buy = new javax.swing.JButton();
        jButton_pay = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jTextField_numberOfItems = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_payment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_view = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jButton_display = new javax.swing.JButton();
        jScrollPane_1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane_2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField_qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalpriceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Product ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Payment");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Change");

        jButton_buy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_buy.setText("BUY");
        jButton_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buyActionPerformed(evt);
            }
        });

        jButton_pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_pay.setText("PAY");
        jButton_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_payActionPerformed(evt);
            }
        });

        bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bill.setText("GENERATE RECEIPT");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        jButton_clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_clear.setText("CLEAR");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jTextField_numberOfItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numberOfItemsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No. of Items");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Price");

        jButton_view.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_view.setText("Product List");
        jButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewActionPerformed(evt);
            }
        });

        jButton_back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jButton_display.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_display.setText("DISPLAY PRODUCTS");
        jButton_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_displayActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity in Stock", "Unit Price"
            }
        ));
        jScrollPane_1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Unit Price", "Total Price"
            }
        ));
        jScrollPane_2.setViewportView(jTable2);

        Area.setColumns(20);
        Area.setRows(5);
        Area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jScrollPane1.setViewportView(Area);

        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("PRINT RECEIPT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POINT OF SALE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(633, 633, 633))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_numberOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_change, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jButton_display)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane_2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bill)
                        .addGap(104, 104, 104)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_view, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_back))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane_1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_display, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_numberOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_view, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addComponent(jScrollPane_2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        this.toBack();
        setVisible(false);
        new Cover().toFront();
        new Cover().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_displayActionPerformed
  
        try {
  
            BufferedReader rdfile = new BufferedReader(new FileReader("items.txt"));

            String[] line = new String[1000];
            String[] temp;
            int num = 100;

            int x = 0;  //read item
            while ((line[x] = rdfile.readLine()) != null) {
                temp = line[x].trim().split("\t"); 
                num += 1;
                model = (DefaultTableModel)jTable1.getModel();
                     model.addRow(new Object [] {                            
                        num, // product ID - column 1
                        temp[0], // product name - column 2
                        temp[1], // quantity - column 3
                        temp[2], // unit price - column 4        
                    });
                x++;
            }
            rdfile.close();

            } catch (IOException e) {
        }                      
    }//GEN-LAST:event_jButton_displayActionPerformed

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed
        Products a = new Products();
        a.setVisible(true);
        a.setDefaultCloseOperation(Products.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_viewActionPerformed

    private void jButton_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buyActionPerformed
        try {
            
            BufferedReader rdfile = new BufferedReader(new FileReader("items.txt"));
            
            String[] itemline = new String[1000];
            String str;
            double price, total;
            int qty = 0, prvQty = 0, newQty = 0;
            boolean found = false, edited = false;
            int id = (Integer.parseInt(jTextField_id.getText()))-101;

            for (int x = 0; (str = rdfile.readLine()) != null; x++) {
                itemline[x] = str;
            }
            rdfile.close();

            int r = Row.getRow();
            for (int i = 0; itemline[i] != null; i++) { 
                if (id == i) { // check if Product ID is equal to the row number
                    found = true;
                    String[] temp = itemline[i].trim().split("\t");
                    qty = Integer.parseInt(jTextField_qty.getText());
                    prvQty = Integer.parseInt(temp[1]);
                    if ((qty > prvQty) && (prvQty != 0)) {
                        JOptionPane.showMessageDialog(null, "Item Shortage!", "Oops!", JOptionPane.WARNING_MESSAGE);
                    }
                    if (prvQty == 0) {
                        JOptionPane.showMessageDialog(null, "Out of Stock!", "Oops!", JOptionPane.WARNING_MESSAGE);
                    }
                    if ((qty <= prvQty) && (prvQty != 0)) { // condition to be satified
                       
                        newQty = prvQty - qty;
                        itemline[i] = temp[0] + "\t" + newQty + "\t" + temp[2]; // replace the quantity of the product in the file by newQty
                        
                        model = (DefaultTableModel)jTable1.getModel();
                        model.setValueAt(newQty, id, 2); // 
                        
                        price = Double.parseDouble(temp[2]);
                        total = qty * price;
                        String itemName = temp[0];  
                        model = (DefaultTableModel)jTable2.getModel();
                        model.addRow(new Object [] {                            
                            itemName,
                            qty,
                            price,
                            total                            
                        });
                        
                        int row = jTable2.getRowCount();
                        int numOfItems = 0;
                        double totalPrice = 0;
                        for (int a= 0; a<row; a++){
                             numOfItems += (Integer.parseInt(jTable2.getValueAt(a, 1).toString()));
                             totalPrice += (Double.parseDouble(jTable2.getValueAt(a,3).toString()));
                        }
                        jTextField_numberOfItems.setText(Integer.toString(numOfItems));
                        jTextField_totalprice.setText(Double.toString(totalPrice));
                        
                        r++;
                        edited = true;
                    }                   
                }              
            }
            
            if (!found) {
                JOptionPane.showMessageDialog(null, jTextField_id.getText() + ": Item Not Available!", "Oops!", JOptionPane.ERROR_MESSAGE);
            }
            if (edited) {
                PrintWriter wrfile = new PrintWriter(new FileWriter("items.txt"));
                for (int i = 0; itemline[i] != null; i++) {
                    wrfile.println(itemline[i]);
                }               
                wrfile.close();
                Row.setRow();
                jButton_pay.setEnabled(true);
                jTextField_id.setText("");
                jTextField_qty.setText("");
            }
                
            jTextField_id.setText("");
            jTextField_qty.setText("");

        } catch (IOException e) {
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!", "", JOptionPane.ERROR_MESSAGE);
            jTextField_id.setText("");
            jTextField_qty.setText("");
        }                                     
    }//GEN-LAST:event_jButton_buyActionPerformed

    private void jButton_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_payActionPerformed
        try {               
            double totalPrice, cash;
            do {  
                cash = Double.parseDouble(jTextField_payment.getText());
                totalPrice = (Double.parseDouble(jTextField_totalprice.getText()));                
                jTextField_payment.setText("");               
                if (cash < totalPrice) {
                    JOptionPane.showMessageDialog(null, "Insufficient Cash!", null, JOptionPane.WARNING_MESSAGE);
                }
            } while (cash < totalPrice);
            jTextField_change.setText("" + (cash - totalPrice));
            jTextField_payment.setText("" + cash);
            jButton_buy.setEnabled(false);
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_jButton_payActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        
        model = (DefaultTableModel)jTable2.getModel();
        
        while (model.getRowCount()> 0){
            for (int i = 0; i<jTable2.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        jButton_pay.setEnabled(true);
        jTextField_numberOfItems.setText("");
        jTextField_payment.setText("");
        jTextField_totalprice.setText("");
        jTextField_change.setText("");
        //Row.setRow(0);
        jButton_buy.setEnabled(true);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jTextField_totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalpriceActionPerformed
        
  
    }//GEN-LAST:event_jTextField_totalpriceActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed

        int row = jTable2.getRowCount();
        double cash = Double.parseDouble(jTextField_payment.getText());
        double change = Double.parseDouble(jTextField_change.getText());
        int items = 0;
        double totalPrice = 0;
       
        model = (DefaultTableModel)jTable2.getModel();
        Date thisDate = new Date(); 
        
        Area.setText(Area.getText() + "\n");
        Area.setText(Area.getText() + "                         24/7 SARI-SARI STORE                           \n");
        Area.setText(Area.getText() + "                    Mataas Na Bldg sa Dancalan St.                      \n");
        Area.setText(Area.getText() + "                           Donsol, Sorsogon                             \n\n");
        Area.setText(Area.getText() + "------------------------------------------------------------------------\n");
        Area.setText(Area.getText() + "Quantity"+"\t"+"Product Name"+"\t\t"+"Total"+"\n");
        Area.setText(Area.getText() + "------------------------------------------------------------------------\n");
        for(int i=0; i<row; i++){
            String name = jTable2.getValueAt(i,0).toString().trim();
            String qty = jTable2.getValueAt(i,1).toString();
            String total = jTable2.getValueAt(i,3).toString();
            Area.setText(Area.getText()+qty+"\t"+name+"\t\t"+total+"\n"); 
        }
        Area.setText(Area.getText() + "------------------------------------------------------------------------\n");
 
        for (int a= 0; a<row; a++){
            items += (Integer.parseInt(jTable2.getValueAt(a, 1).toString()));
            totalPrice += (Double.parseDouble(jTable2.getValueAt(a,3).toString()));
        }
        
        Area.setText(Area.getText() +items+"  ITEM(S)"+"\t\t"+"TOTAL:"+"\t"+totalPrice+"\n");
        Area.setText(Area.getText() +"    "+"\t\t"+"CASH:"+"\t"+cash+"\n");
        Area.setText(Area.getText() +"    "+"\t\t"+"CHANGE:"+"\t"+change+"\n\n");
        Area.setText(Area.getText() + "------------------------------------------------------------------------\n\n");
        Area.setText(Area.getText() + "                  CASHIER: JUAN DELA CRUZ                     \n");
        Area.setText(Area.getText() + "                   BAGGER: CARDO DALISAY                      \n\n");   
        Area.setText(Area.getText() + "                 "+thisDate+"                               \n");    
    }//GEN-LAST:event_billActionPerformed

    private void jTextField_numberOfItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numberOfItemsActionPerformed
       
    }//GEN-LAST:event_jTextField_numberOfItemsActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {      
            Area.print();
        }catch(Exception e){}
    }//GEN-LAST:event_printActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        model = (DefaultTableModel)jTable2.getModel();
        
        int selectedRow = jTable2.getSelectedRow();
        model.removeRow(selectedRow);
        
        int row = jTable2.getRowCount();
        int numOfItems = 0;
        double totalPrice = 0;
                        
        for (int a= 0; a<row; a++){
            numOfItems += (Integer.parseInt(jTable2.getValueAt(a, 1).toString()));
            totalPrice += (Double.parseDouble(jTable2.getValueAt(a,3).toString()));
        }
        jTextField_numberOfItems.setText(Integer.toString(numOfItems));
        jTextField_totalprice.setText(Double.toString(totalPrice));
    }//GEN-LAST:event_jButton_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton bill;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_buy;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_display;
    private javax.swing.JButton jButton_pay;
    private javax.swing.JButton jButton_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_1;
    private javax.swing.JScrollPane jScrollPane_2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_change;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_numberOfItems;
    private javax.swing.JTextField jTextField_payment;
    private javax.swing.JTextField jTextField_qty;
    private javax.swing.JTextField jTextField_totalprice;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
